##Planilha autómatica pequeno projeto
print('seja bem vindo ao criador de planilha')
grupo1 = input('Escolha o nome do primeiro grupo de informações. exemplo: Nomes, telefones, rgs e etc:')
n1 = input('Digite aqui o intem que quer usar no primeiro grupo criado. exemplo: nome = rogerio.:')
n2 = input('item2:')
n3 = input('item3:')
n4 = input('item4:')
n5 = input('item5:')
grupo2 = input('Escolha o nome do segundo grupo de informações:')
i1 = input('Digite aqui o item um quer usar no segundo grupo criado:')
i2 = input('item2:')
i3 = input('Item3:')
i4 = input('item4:')
i5 = input('item5:')
grupo3 = input('Escolha o nome do terceiro grupo de informações')
m1 =input('item1:')
m2 =input('item2:')
m3 =input('item3:') 
m4 =input('item4:')
m5 =input('item5:')
print(f'\n {grupo1:<20} {grupo2:^20} {grupo3:>20}')
print(f'\n {n1:<20}', end=''*20)
print(f' {i1:^20}', end=''*20)
print(f' {m1:>20}')
print(f'\n {n2:<20}', end=''*20)
print(f' {i2:^20}', end=''*20)
print(f' {m2:>20}') 
print(f'\n {n3:<20}', end=''*20)
print(f' {i3:^20}', end=''*20)
print(f' {m3:>20}')
print(f'\n {n4:<20}', end=''*20)
print(f' {i4:^20}', end=''*20)
print(f' {m4:>20}')
print(f'\n {n5:<20}', end=''*20)
print(f' {i5:^20}', end=''*20)
print(f' {m5:>20}',)

print('FEITO POR COCA GELADA!')